### ISSUE TITLE
create proper frontend

### ISSUE THREAD

**Issue by frederic-schwarz** [archilogic-com/3dio-floor-plan-app#1]
adapt frontend from spaces.archilogic.com/order to work with 3dio-floor-plan-app
* let's remove jquery in favor of these few convenience functions:
https://github.com/archilogic-com/3dio-js/blob/master/src/utils/ui/common/dom-el.js
* javascript code should all end up in app.js

**Comment by frederic-schwarz** [comment]
initial commit after porting frontend from spaces https://github.com/archilogic-com/3dio-floor-plan-app/commit/751f0313ed91cc6ac99891e6f7ca565d8f0218d4

**Comment by mope1** [comment]
https://github.com/archilogic-com/3dio-floor-plan-app/pull/3
