### ISSUE TITLE
What are the reasons for rejected Floorplans

### ISSUE THREAD

**Issue by Fischaela** [archilogic-com/3dio-floor-plan-app#14]
Hi :) In your code https://github.com/archilogic-com/3dio-floor-plan-app/blob/master/api/on-conversion-status-update.js#L90 there are multiple reasons for a floorplan rejection:

```
// conversion has unfortunately been reject. most likely due to one of the following reasons:
// NO_FLOORPLAN, UNCLEAR_FLOORPLAN, MULTIPLE_LEVELS, INCLINED_CEILING
// Read more about converion limitiations: https://3d.io/docs/api/1/basic-3d-model.html
```

The URL you're referring to is a 404 :( Can you explain, what the four reasons are exactly? I am trying to write descriptive messages for a user. Thanks!

**Comment by AVGP** [comment]
`NO_FLOORPLAN`: The image isn't showing a floorplan
`UNCLEAR_FLOORPLAN`: The image is possibly a floorplan, but it's unclear how to model it (e.g. blurry, unclear text labels, badly hand-drawn)
`MULTIPLE_LEVELS` The document you uploaded contains multiple floors of a building and it's unclear which one should be modeled. The API doesn't support multi-floor situations.
`INCLINED_CEILING` - the floorplan indicates slanted roofs (schraegdach) and that isn't supported.

**Comment by Fischaela** [comment]
@AVGP Thanks so much, Martin 🍰 ❤️
