### ISSUE TITLE
error on request

### ISSUE THREAD

**Issue by tomas-polach** [archilogic-com/3dio-floor-plan-app#5]
![3d_io_floor_plan_app](https://user-images.githubusercontent.com/6619499/29968430-f45fd4e8-8f1b-11e7-8608-7d5617ae5265.jpg)

tested with this model:
![aaa](https://user-images.githubusercontent.com/6619499/29968427-f2241284-8f1b-11e7-9999-946a3dd0fd74.jpg)

**Comment by mope1** [comment]
was caused by new release if API, got fixed
