### ISSUE TITLE
https://io3d-floor-plan-app.herokuapp.com/ not working

### ISSUE THREAD

**Issue by frederic-schwarz** [archilogic-com/3dio-floor-plan-app#6]
* reproduce:
  * upload image
  * click convert

* result:

Sending request failed:{ "jsonrpc": "2.0", "error": { "code": -32600, "message": "Error in calling 3d.io API. RPC ID: 21759848699817860000" }, "id": 21759848699817860000 }
Check your email for details

* email:

Error in calling 3d.io API.

Error in calling 3d.io API. Details: “Invalid API key. Maybe you used your publishable key instead of your secret key?” Original Request: {

"jsonrpc": "2.0",
"method": "FloorPlan.convertToBasic3dModel",
"params": {
  "floorPlan": "https://storage.3d.io/temp/2017-09-08_08-07-10_p4xG9l/human3.png",
  "address": "",
  "email": "fs@3d.io"
},
"id": 21759848699817860000
}

**Comment by m-ke** [comment]
The API key used in the heroku app is wrong.

**Comment by m-ke** [comment]
I just changed the Secret API key to the Archilogic one.

**Comment by tomas-polach** [comment]
@m-ke thanks! where did you change it? in heroku env variables?

**Comment by m-ke** [comment]
Yes, I changed the Heroku environment variable
