### ISSUE TITLE
get the conversion id in the end, what to do next?

### ISSUE THREAD

**Issue by sky790312** [archilogic-com/3dio-floor-plan-app#7]
I have tried this 2d to 3d floor plan conversion here:

https://github.com/archilogic-com/3dio-floor-plan-app

I got the conversion id in the end. What to do next?

I found out the conversion in firebase db status shows "IN_PROGRESS", will it change the conversion in firebase db status to "COMPLETED" automatically when it's completed?

Will I get the 3d ojbect file back?

Thanks

**Comment by AVGP** [comment]
Hey there!

Thanks for your inquiry - sorry it took a bit for us to respond.
Here's the answer: https://stackoverflow.com/questions/46171956/convert-floor-plan-to-3d
