### ISSUE TITLE
use https://floor-plan.3d.io domain

### ISSUE THREAD

**Issue by tomas-polach** [archilogic-com/3dio-floor-plan-app#8]
the app is currently running on https://io3d-floor-plan-app.herokuapp.com/

to be consistent with our product line up we should run it on https://floor-plan.3d.io

this is possible by:
- setting up Route53 C-NAME DNS records pointing to heroku
- adding domain in heroku app settings

i also suggest to set up https://floorplan.3d.io pointing to this instance because it's not uncommon writing "floorplan" in one word and some i think some redundancy can't harm in this case?

**Comment by tomas-polach** [comment]
@mope1 hope you are ok with taking this one? i think it's a good opportunity to get familiar with our DNS infrastructure

**Comment by mope1** [comment]
it's almost done but the post request bounces with access denied

will have a look tomorrow

**Comment by mope1** [comment]
i found the dash to be kinda clunky so i put it to https://floorplan.3d.io if thats ok

otherwise i can easily move once i found out the correct cloudfront settings

**Comment by tomas-polach** [comment]
@mope1 do you need cloudfront? i think you could just set up a CNAME record pointing to heroku. and in heroku set the DNS settings
